from src.sorting import sort_by


jobs = [
    {
        "job_title": "RN/LPN (PRN)",
        "company": "Friedwald Center for Rehabilitation and Nursing",
        "state": "NY",
        "city": "New York",
        "min_salary": "65665",
        "max_salary": "87057",
        "industry": "Biotech & Pharmaceuticals",
        "rating": "2.5",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "345",
    },
    {
        "job_title": "Regional Vice President",
        "company": "PlanMember Financial",
        "state": "NY",
        "city": "New York",
        "min_salary": "84236",
        "max_salary": "162105",
        "industry": "Finance",
        "rating": "3.6",
        "date_posted": "2020-04-27",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "348",
    },
    {
        "job_title": "Doctor of Veterinary Medicine",
        "company": "Banfield Pet Hospital",
        "state": "NY",
        "city": "Staten Island",
        "min_salary": "81991",
        "max_salary": "120117",
        "industry": "Health Care",
        "rating": "3.2",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "353",
    },
    {
        "job_title": "Hair Stylist",
        "company": "JK Salon and Spa",
        "state": "NJ",
        "city": "Fort Lee",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "354",
    },
    {
        "job_title": "RN / LPN",
        "company": "Star Pediatric Home Care Agency",
        "state": "NJ",
        "city": "Jersey City",
        "min_salary": "48000",
        "max_salary": "75000",
        "industry": "Health Care",
        "rating": "4.5",
        "date_posted": "2020-04-29",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "355",
    },
]

sorted_by_min_salary = [
    {
        "job_title": "RN / LPN",
        "company": "Star Pediatric Home Care Agency",
        "state": "NJ",
        "city": "Jersey City",
        "min_salary": "48000",
        "max_salary": "75000",
        "industry": "Health Care",
        "rating": "4.5",
        "date_posted": "2020-04-29",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "355",
    },
    {
        "job_title": "RN/LPN (PRN)",
        "company": "Friedwald Center for Rehabilitation and Nursing",
        "state": "NY",
        "city": "New York",
        "min_salary": "65665",
        "max_salary": "87057",
        "industry": "Biotech & Pharmaceuticals",
        "rating": "2.5",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "345",
    },
    {
        "job_title": "Doctor of Veterinary Medicine",
        "company": "Banfield Pet Hospital",
        "state": "NY",
        "city": "Staten Island",
        "min_salary": "81991",
        "max_salary": "120117",
        "industry": "Health Care",
        "rating": "3.2",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "353",
    },
    {
        "job_title": "Regional Vice President",
        "company": "PlanMember Financial",
        "state": "NY",
        "city": "New York",
        "min_salary": "84236",
        "max_salary": "162105",
        "industry": "Finance",
        "rating": "3.6",
        "date_posted": "2020-04-27",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "348",
    },
    {
        "job_title": "Hair Stylist",
        "company": "JK Salon and Spa",
        "state": "NJ",
        "city": "Fort Lee",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "354",
    },
]

sorted_by_max_salary = [
    {
        "job_title": "Regional Vice President",
        "company": "PlanMember Financial",
        "state": "NY",
        "city": "New York",
        "min_salary": "84236",
        "max_salary": "162105",
        "industry": "Finance",
        "rating": "3.6",
        "date_posted": "2020-04-27",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "348",
    },
    {
        "job_title": "Doctor of Veterinary Medicine",
        "company": "Banfield Pet Hospital",
        "state": "NY",
        "city": "Staten Island",
        "min_salary": "81991",
        "max_salary": "120117",
        "industry": "Health Care",
        "rating": "3.2",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "353",
    },
    {
        "job_title": "RN/LPN (PRN)",
        "company": "Friedwald Center for Rehabilitation and Nursing",
        "state": "NY",
        "city": "New York",
        "min_salary": "65665",
        "max_salary": "87057",
        "industry": "Biotech & Pharmaceuticals",
        "rating": "2.5",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "345",
    },
    {
        "job_title": "RN / LPN",
        "company": "Star Pediatric Home Care Agency",
        "state": "NJ",
        "city": "Jersey City",
        "min_salary": "48000",
        "max_salary": "75000",
        "industry": "Health Care",
        "rating": "4.5",
        "date_posted": "2020-04-29",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "355",
    },
    {
        "job_title": "Hair Stylist",
        "company": "JK Salon and Spa",
        "state": "NJ",
        "city": "Fort Lee",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "354",
    },
]

sorted_by_date_posted = [
    {
        "job_title": "Hair Stylist",
        "company": "JK Salon and Spa",
        "state": "NJ",
        "city": "Fort Lee",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-07",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "354",
    },
    {
        "job_title": "Doctor of Veterinary Medicine",
        "company": "Banfield Pet Hospital",
        "state": "NY",
        "city": "Staten Island",
        "min_salary": "81991",
        "max_salary": "120117",
        "industry": "Health Care",
        "rating": "3.2",
        "date_posted": "2020-05-02",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "353",
    },
    {
        "job_title": "RN / LPN",
        "company": "Star Pediatric Home Care Agency",
        "state": "NJ",
        "city": "Jersey City",
        "min_salary": "48000",
        "max_salary": "75000",
        "industry": "Health Care",
        "rating": "4.5",
        "date_posted": "2020-04-29",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "355",
    },
    {
        "job_title": "RN/LPN (PRN)",
        "company": "Friedwald Center for Rehabilitation and Nursing",
        "state": "NY",
        "city": "New York",
        "min_salary": "65665",
        "max_salary": "87057",
        "industry": "Biotech & Pharmaceuticals",
        "rating": "2.5",
        "date_posted": "2020-04-28",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "345",
    },
    {
        "job_title": "Regional Vice President",
        "company": "PlanMember Financial",
        "state": "NY",
        "city": "New York",
        "min_salary": "84236",
        "max_salary": "162105",
        "industry": "Finance",
        "rating": "3.6",
        "date_posted": "2020-04-27",
        "valid_until": "2020-06-07",
        "job_type": "FULL_TIME",
        "id": "348",
    },
]


def test_sort_by_criteria():
    sort_by(jobs, "min_salary")
    assert jobs == sorted_by_min_salary

    sort_by(jobs, "max_salary")
    assert jobs == sorted_by_max_salary

    sort_by(jobs, "date_posted")
    assert jobs == sorted_by_date_posted
